version: '3'

tasks:
  mypy:
    cmds:
      - poetry run mypy give_money_bot --show-traceback --ignore-missing-imports --follow-imports=skip --config-file mypy.ini

  build:
    cmds:
      - poetry install

  build-release:
    cmds:
      - poetry install --no-dev

  black:
    cmds:
      - poetry run black give_money_bot

