version: '3'

tasks:
  mypy:
    cmds:
      - poetry run mypy give_money_bot --show-traceback --ignore-missing-imports --follow-imports=skip --config-file mypy.ini

  build:
    cmds:
      - poetry install

  build-release:
    cmds:
      - poetry install --no-dev

  run:
    cmds:
      - poetry run bot

  black:
    cmds:
      - poetry run black give_money_bot
  
  dbuild:
    cmds:
      - podman build -t give-money-bot .

  drun:
    cmds:
      - podman run --env-file .env -v ./data:/prod/data -it give-money-bot "python -m give_money_bot"
