"""Create indexes

Revision ID: 36128b8403ca
Revises: d6f21c02a1c9
Create Date: 2022-09-21 23:57:12.383549

"""
import sqlalchemy as sa  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision = '36128b8403ca'
down_revision = 'd6f21c02a1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credits_from_id'), ['from_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credits_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_credits_returned'), ['returned'], unique=False)
        batch_op.create_index(batch_op.f('ix_credits_to_id'), ['to_id'], unique=False)

    with op.batch_alter_table('user_vision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_vision_show_type'), ['show_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_vision_show_user_id'), ['show_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_vision_user_id'), ['user_id'], unique=False)
        batch_op.create_index('user_pair_idx', ['user_id', 'show_user_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tg_alias'), ['tg_alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_tg_alias'))

    with op.batch_alter_table('user_vision', schema=None) as batch_op:
        batch_op.drop_index('user_pair_idx')
        batch_op.drop_index(batch_op.f('ix_user_vision_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_vision_show_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_vision_show_type'))

    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credits_to_id'))
        batch_op.drop_index(batch_op.f('ix_credits_returned'))
        batch_op.drop_index(batch_op.f('ix_credits_id'))
        batch_op.drop_index(batch_op.f('ix_credits_from_id'))

    # ### end Alembic commands ###
