"""Add users tabel

Revision ID: 711669486eee
Revises: 9ea314271a27
Create Date: 2021-12-22 18:56:53.630317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "711669486eee"
down_revision = "9ea314271a27"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("credits", schema=None) as batch_op:
        batch_op.create_foreign_key("fk_creditor_id", "users", ["to_id"], ["user_id"])
        batch_op.create_foreign_key("fk_debtor_id", "users", ["from_id"], ["user_id"])
    # ### end Alembic commands ###

    op.bulk_insert(
        users_table,
        [
            {"user_id": 447411595, "name": "Коля", "admin": True},
            {"user_id": 697676993, "name": "Игнат", "admin": False},
            {"user_id": 419576201, "name": "Саша", "admin": False},
            {"user_id": 406974543, "name": "Никита", "admin": False},
            {"user_id": 441085220, "name": "Чонг", "admin": False},
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credits", schema=None) as batch_op:
        batch_op.drop_constraint("fk_debtor_id", type_="foreignkey")
        batch_op.drop_constraint("fk_creditor_id", type_="foreignkey")

    op.drop_table("users")
    # ### end Alembic commands ###
