"""Add user substitution

Revision ID: d6f21c02a1c9
Revises: 475aa5c976a6
Create Date: 2022-09-01 23:30:18.511073

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd6f21c02a1c9'
down_revision = '475aa5c976a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('substituted_user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('substituted_user_id')

    # ### end Alembic commands ###
