"""Move user vision to new table

Revision ID: e5a51715598b
Revises: a9f779086e6c
Create Date: 2022-04-20 19:33:00.044661

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e5a51715598b'
down_revision = 'a9f779086e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: the auto-generated upgrade only dropped users.show_users and never
    # created the user_vision table this revision is named after — so a fresh
    # `alembic upgrade head` failed later in 36128b8403ca (Create indexes) with
    # "no such table: user_vision". The table was historically created out-of-band
    # by Base.metadata.create_all(). Create it here explicitly; indexes are added
    # by the later 36128b8403ca revision. Already-migrated DBs (prod) are past this
    # revision and never re-run it.
    op.create_table(
        'user_vision',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('show_user_id', sa.Integer(), nullable=False),
        sa.Column('show_type', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id']),
        sa.ForeignKeyConstraint(['show_user_id'], ['users.user_id']),
        sa.PrimaryKeyConstraint('user_id', 'show_user_id'),
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('show_users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_users', sa.VARCHAR(), nullable=True))

    op.drop_table('user_vision')
    # ### end Alembic commands ###
