"""Move user vision to new table

Revision ID: e5a51715598b
Revises: a9f779086e6c
Create Date: 2022-04-20 19:33:00.044661

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e5a51715598b'
down_revision = 'a9f779086e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('show_users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_users', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
