version: '3.7'
services:
  bot:
    image: ghcr.io/platun0v/give-money-bot:latest
    command: "python -m give_money_bot"
    container_name: give-money-bot-image
    volumes:
      - ./data:/prod/data
    env_file:
      - ./.env
    restart: on-failure
