name: Build image

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  workflow_run:
    workflows: [ "Test" ]
    types:
      - completed

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build and push amd64, arm32v7
        env:
            DOCKER_IMAGE_NAME: give-money-bot
            GITHUB_REF: ${{ github.ref }}
        run: |
          ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
          docker buildx build \
              --platform linux/amd64,linux/arm/v7 \
              --push \
              --target production \
              --tag ghcr.io/${{ github.repository_owner }}/$DOCKER_IMAGE_NAME:$ref \
              --tag ghcr.io/${{ github.repository_owner }}/$DOCKER_IMAGE_NAME:latest \
              .