name: Docker container builder

on:
  push:
    branches: [ release ]

jobs:

  build_app_image:
    runs-on: ubuntu-latest
    steps:

      - name: Pulling new containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            cd give_money_bot
            ./update.sh
