name: Test

on: [push, pull_request]

jobs:
  test-types:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Create venv
        shell: bash
        run: |
          pip install virtualenv
          python -m virtualenv venv
      - name: Install dependencies
        shell: bash
        run: |
          pip install poetry
          source venv/bin/activate
          task install
      - name: Type hint test
        shell: bash
        run: |
          source venv/bin/activate
          task mypy

  test-parser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Test
        shell: bash
        run: task test-docker
