name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: false
        default: 'latest'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy new version with hook
        env:
          UPDATER_KEY: ${{ secrets.UPDATE_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
        run: curl -s "https://platun0v.ru/hooks/give-money-bot?token=${UPDATER_KEY}&version=${VERSION}"
